; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "test teip v05 tcp modbus"
#define MyAppVersion "0.5"
#define MyAppPublisher "ТЭиП Company, Inc."
#define MyAppURL "https://tep-mspk.ru/"
#define MyAppExeName "tcp_test.exe"
#define MyAppAssocName MyAppName + " File"
#define MyAppAssocExt ".myp"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{3A2CF3FC-DF7B-457E-A72F-FE65E01869E2}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
ChangesAssociations=yes
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputDir=C:\rrr\LAZ_IINDI10_v3\install_inform
OutputBaseFilename=test modbus tcp teip
SetupIconFile=C:\rrr\LAZ_IINDI10_v3\SERVER_CLIENT_v0_5\SERVER_CLIENT\test_modbus.ico
SolidCompression=yes
WizardStyle=modern dynamic

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "russian"; MessagesFile: "compiler:Languages\Russian.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\rrr\LAZ_IINDI10_v3\SERVER_CLIENT_v0_5\SERVER_CLIENT\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\rrr\LAZ_IINDI10_v3\SERVER_CLIENT_v0_5\SERVER_CLIENT\crc_16.pas"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\rrr\LAZ_IINDI10_v3\SERVER_CLIENT_v0_5\SERVER_CLIENT\eee"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\rrr\LAZ_IINDI10_v3\SERVER_CLIENT_v0_5\SERVER_CLIENT\ip_tcp"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\rrr\LAZ_IINDI10_v3\SERVER_CLIENT_v0_5\SERVER_CLIENT\iphist.dat"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\rrr\LAZ_IINDI10_v3\SERVER_CLIENT_v0_5\SERVER_CLIENT\kkk"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\rrr\LAZ_IINDI10_v3\SERVER_CLIENT_v0_5\SERVER_CLIENT\project1.lps"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\rrr\LAZ_IINDI10_v3\SERVER_CLIENT_v0_5\SERVER_CLIENT\project1.res"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\rrr\LAZ_IINDI10_v3\SERVER_CLIENT_v0_5\SERVER_CLIENT\tcp_inp"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\rrr\LAZ_IINDI10_v3\SERVER_CLIENT_v0_5\SERVER_CLIENT\tcp_mas"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\rrr\LAZ_IINDI10_v3\SERVER_CLIENT_v0_5\SERVER_CLIENT\tcp_str"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\rrr\LAZ_IINDI10_v3\SERVER_CLIENT_v0_5\SERVER_CLIENT\test_modbus.ico"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExt}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

